### ISSUE TITLE
Can Smartloop use Google API?

### ISSUE THREAD

**Issue by yevhen-shulha** [SmartloopAI/smartloop-feedback#19]
Hi, 

I need to search a google spreadsheet -- can a Smartloop bot do that? If yes, can you give me an example of a spreadsheets.values.get request? (https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get)

I mean, where do I put all the API_KEY, CLIENT_ID, valueRenderOption and SCOPE stuff. 

Thank you!

**Comment by mehfuzh** [comment]
Hi Yevhen,

You can use the config section to put your API_KEY :
https://docs.smartloop.ai/developer-features.html#using-variables-in-script-block

Basically, you keep your sensitive data away from the bot and set them as config vars, so that from the JSON API you can do `{{config.key}}`. 

Here is an example of how I am pulling a google sheet using `JSON API`:

<img width="677" alt="sheet-get" src="https://user-images.githubusercontent.com/141204/86496383-12399700-bd32-11ea-87a3-74db86f431b6.png">

```
https://sheets.googleapis.com/v4/spreadsheets/{{sheet_id}}?key={{config.key}}
 ````

I have set the `api` and `sheet_id` in the `setttings-> configuration` in the following way:

<img width="714" alt="config" src="https://user-images.githubusercontent.com/141204/86496472-79efe200-bd32-11ea-9f68-9be472764bb5.png">


__Use the `google` API console to create an API_KEY, you will also have to make sure that the account that is used to create the API_KEY is the account where the sheet is created or mark the sheet as "anyone with the link".__


Hope this helps

**Comment by yevhen-shulha** [comment]
Yes, thank you!
