### ISSUE TITLE
Use 7 rows for Viber cards

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#23]
**Is your feature request related to a problem? Please describe.**
 
Max rows for Viber's rich media template is 7 but on Smartloop only 6 is used.  

**Describe the solution you'd like**

Use all 7 rows instead of 6. 

**Describe alternatives you've considered**

N/A

**Additional context**

We'd like to make more space for the images since it gets adjusted whenever a new button is added. 

![image](https://user-images.githubusercontent.com/20976789/88038794-4ce85f80-cb79-11ea-978e-d93ffb332764.png)

**Comment by mehfuzh** [comment]
Viber has max limit of 6 rows/ column.  You won't able to do it 7 rows. You will have to break the carousel in two groups.

**Comment by vxzry** [comment]
Hi, sorry for the confusion, I was pertaining to the number of rows per card. Please the image below for your reference.  

![image](https://user-images.githubusercontent.com/20976789/88124788-7bf5e400-cc00-11ea-846a-60748368c948.png)

**Comment by mehfuzh** [comment]
I have checked the issue. It is a bit different from facebook, ideally in Viber its 6 rows and 6 columns settings (max). If you count the maximum number of rows here it is 6 that includes image, title, and 4 buttons. Therefore, when you are using a carousel it is going to skip the rest to ensure that next cards are rendered correctly. I would recommend updating how you design your carousel, instead of having 7 buttons in one card.
